M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Fri 25 Sep 2026 05:20:45 PM CDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-09-25T17:20:45-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X0.4947Y-0.4154
X0.6856Y-0.4154
T2
X0.4829Y-0.2961
X0.6974Y-0.2961
M30
