#!/usr/bin/env python3
"""Turn the pages in web/ into src/webpage.c.

The page is served straight out of flash, so it lives in the firmware as a
C string.  Edit page.html and run this; never hand-edit the escaping.

    python3 web/genpage.py

Verify a round trip at any time with:

    python3 web/genpage.py --check
"""
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
PAGES = [("page.html", "web_page"), ("setup.html", "web_setup")]
DST = os.path.join(ROOT, "src", "webpage.c")

LICENSE = """
/*
   Copyright (c) 2026 Daniel Marks

  This software is provided 'as-is', without any express or implied
  warranty. In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/
"""


def escape(s):
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\t":
            out.append("\\t")
        elif ch == "?":
            out.append("\\?")          # so no trigraph can ever form
        elif ord(ch) < 32:
            out.append("\\%03o" % ord(ch))
        elif ord(ch) > 126:
            out.append("".join("\\%03o" % b for b in ch.encode()))
        else:
            out.append(ch)
    return "".join(out)


def unescape(c_source, symbol):
    """Recover a page from the generated C, to prove the escaping is sound."""
    body = c_source.split("const char %s[] =" % symbol, 1)[1].split(";\n", 1)[0]
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"', body, re.S)
    out = bytearray()
    for p in parts:
        i = 0
        while i < len(p):
            if p[i] != "\\":
                out.append(ord(p[i])); i += 1
                continue
            n = p[i + 1]
            if n in "01234567":
                out.append(int(p[i + 1:i + 4], 8)); i += 4
            elif n == "t":
                out.append(9); i += 2
            elif n == "n":
                out.append(10); i += 2
            else:
                out.append(ord(n)); i += 2
    return out.decode("utf-8")


def one(html, symbol):
    lines = html.split("\n")
    body = "\n".join(
        '  "%s%s"' % (escape(l), "\\n" if i < len(lines) - 1 else "")
        for i, l in enumerate(lines)
    )
    return ("const char %s[] =\n" % symbol + body + ";\n\n"
            "const uint32_t %s_len = (uint32_t)(sizeof(%s) - 1u);\n\n"
            % (symbol, symbol))


def stamp(html):
    """Substitute __WEBVER__ with a hash of the page's own source.

    The open browser tab keeps itself current by polling, never by
    reloading, so after a reflash it can go on running the JavaScript it
    loaded hours ago.  The page carries the version it was generated from
    and compares it against the one the firmware reports, so a stale tab
    can say so instead of quietly misbehaving.
    """
    ver = hashlib.sha256(html.encode("utf-8")).hexdigest()[:8]
    return html.replace("__WEBVER__", ver), ver


def build(sources):
    out = (
        "/* webpage.c - the pages the web interface serves.\n"
        "   GENERATED by web/genpage.py from the HTML in web - do not edit by hand.\n"
        "   Edit the HTML and regenerate. */\n"
        + LICENSE
        + '\n#include <stdint.h>\n#include "webui.h"\n\n'
    )
    for html, symbol in sources:
        out += one(html, symbol)
    return out


def main():
    raw = [(open(os.path.join(HERE, f), encoding="utf-8").read(), sym)
           for f, sym in PAGES]
    sources, ver = [], ""
    for html, sym in raw:
        html, v = stamp(html)
        if sym == "web_page":
            ver = v
        sources.append((html, sym))
    out = build(sources) + 'const char web_version[] = "%s";\n' % ver

    for html, sym in sources:
        if unescape(out, sym) != html:
            sys.exit("%s does not round trip - refusing to write" % sym)

    if "--check" in sys.argv:
        cur = open(DST, encoding="utf-8").read() if os.path.exists(DST) else ""
        if cur != out:
            sys.exit("%s is stale - run: python3 web/genpage.py" % DST)
        print("webpage.c matches " + ", ".join(f for f, _ in PAGES)
              + " (%d bytes, version %s)"
              % (sum(len(h) for h, _ in sources), ver))
        return

    open(DST, "w", encoding="utf-8").write(out)
    print("wrote %s from %s (%d bytes, version %s)"
          % (DST, ", ".join(f for f, _ in PAGES),
             sum(len(h) for h, _ in sources), ver))


main()
