/* webpage.c - the web interface page.
   GENERATED from web/page.html by web/genpage.py - do not edit by hand.
   Edit the HTML and regenerate. */

/*
   Copyright (c) 2026 Daniel Marks

  This software is provided 'as-is', without any express or implied
  warranty. In no event will the authors be held liable for any damages
  arising from the use of this software.

  Permission is granted to anyone to use this software for any purpose,
  including commercial applications, and to alter it and redistribute it
  freely, subject to the following restrictions:

  1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
  2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
  3. This notice may not be removed or altered from any source distribution.
*/

#include <stdint.h>
#include "webui.h"

const char web_page[] =
  "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">\n"
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
  "<title>Synchronizer</title><style>\n"
  ":root{--bg:#f5f6f7;--fg:#14161a;--dim:#5b636b;--line:#dde1e5;--card:#fff;--acc:#2a78d6;--warn:#c8521f;--ok:#1b7f4b}\n"
  "@media(prefers-color-scheme:dark){:root{--bg:#15171a;--fg:#eef1f4;--dim:#98a0a8;--line:#2a2f35;--card:#1c1f23;--acc:#5c9ded;--warn:#e07a45;--ok:#4bbd82}}\n"
  "*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);\n"
  "font:14px/1.45 system-ui,-apple-system,Segoe UI,Roboto,sans-serif}\n"
  ".wrap{max-width:940px;margin:0 auto;padding:18px 14px 48px}\n"
  "h1{font-size:19px;margin:0;letter-spacing:-.01em}\n"
  "header{display:flex;flex-wrap:wrap;gap:10px;align-items:baseline;justify-content:space-between;\n"
  "border-bottom:1px solid var(--line);padding-bottom:10px;margin-bottom:16px}\n"
  ".sub{color:var(--dim);font-size:12px;font-family:ui-monospace,Menlo,Consolas,monospace}\n"
  ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(290px,1fr));gap:14px}\n"
  "section{background:var(--card);border:1px solid var(--line);border-radius:4px;padding:13px 14px 15px}\n"
  "h2{font-size:11px;letter-spacing:.13em;text-transform:uppercase;color:var(--dim);margin:0 0 10px;font-weight:600}\n"
  "table{width:100%;border-collapse:collapse}\n"
  "td{padding:2px 0;vertical-align:baseline}\n"
  "td.k{color:var(--dim);white-space:nowrap;padding-right:10px}\n"
  "td.v{text-align:right;font-family:ui-monospace,Menlo,Consolas,monospace;font-variant-numeric:tabular-nums}\n"
  ".row{display:flex;gap:6px;align-items:center;margin-top:7px;flex-wrap:wrap}\n"
  "label{color:var(--dim);font-size:12px;min-width:62px}\n"
  "input{width:84px;padding:4px 6px;border:1px solid var(--line);border-radius:3px;background:var(--bg);\n"
  "color:var(--fg);font-family:ui-monospace,Menlo,Consolas,monospace;font-size:13px}\n"
  "select{padding:4px;border:1px solid var(--line);border-radius:3px;background:var(--bg);color:var(--fg);font-size:13px}\n"
  "button{padding:5px 11px;border:1px solid var(--line);border-radius:3px;background:var(--bg);color:var(--fg);\n"
  "font-size:13px;cursor:pointer}\n"
  "button:hover{border-color:var(--acc);color:var(--acc)}\n"
  "button.p{background:var(--acc);border-color:var(--acc);color:#fff}\n"
  "button.p:hover{opacity:.88;color:#fff}\n"
  "button:disabled{opacity:.45;cursor:default}\n"
  "canvas{width:100%;height:130px;display:block;margin-top:9px;border:1px solid var(--line);border-radius:3px}\n"
  ".pill{font-size:11px;padding:2px 7px;border-radius:9px;border:1px solid var(--line);font-family:ui-monospace,monospace}\n"
  ".on{color:var(--ok);border-color:var(--ok)}.off{color:var(--dim)}\n"
  ".bad{color:var(--warn);border-color:var(--warn)}\n"
  ".note{color:var(--dim);font-size:11.5px;margin-top:8px}\n"
  ".wide{grid-column:1/-1}\n"
  "</style></head><body><div class=\"wrap\">\n"
  "<header><h1>Synchronizer</h1>\n"
  "<div class=\"sub\"><span id=\"net\">-</span> &middot; <span id=\"job\">idle</span></div></header>\n"
  "\n"
  "<div class=\"grid\">\n"
  "\n"
  "<section><h2>Loop</h2>\n"
  "<table>\n"
  "<tr><td class=\"k\">state</td><td class=\"v\"><span id=\"lstate\" class=\"pill\">-</span></td></tr>\n"
  "<tr><td class=\"k\">phase error</td><td class=\"v\"><span id=\"lerr\">-</span> us</td></tr>\n"
  "<tr><td class=\"k\">smoothed</td><td class=\"v\"><span id=\"lfilt\">-</span> us</td></tr>\n"
  "<tr><td class=\"k\">events</td><td class=\"v\"><span id=\"lev\">-</span></td></tr>\n"
  "<tr><td class=\"k\">pendulum drift</td><td class=\"v\"><span id=\"ldrift\">-</span> ppb</td></tr>\n"
  "<tr><td class=\"k\">credit</td><td class=\"v\"><span id=\"lcred\">-</span> ns</td></tr>\n"
  "<tr><td class=\"k\">hand offset</td><td class=\"v\"><span id=\"loff\">-</span> ms</td></tr>\n"
  "</table>\n"
  "<div class=\"row\"><button id=\"ctlbtn\" class=\"p\">-</button>\n"
  "<button onclick=\"act('resetloop')\">Re-acquire</button></div>\n"
  "<div class=\"row\"><label>kp/ki</label><input id=\"kp\"><input id=\"ki\">\n"
  "<label style=\"min-width:34px\">slew</label><input id=\"slew\" style=\"width:62px\">\n"
  "<button onclick=\"cfg('kp,ki,slew')\">Apply</button></div>\n"
  "<div class=\"row\"><label>offset ms</label><input id=\"offms\" value=\"0\">\n"
  "<button onclick=\"act('offset&ms='+v('offms'))\">Walk hands</button></div>\n"
  "<div class=\"note\">Positive offset makes the hands read later. The loop slews there at the rate limit; it never jumps.</div>\n"
  "</section>\n"
  "\n"
  "<section><h2>Clock</h2>\n"
  "<table>\n"
  "<tr><td class=\"k\">swing period</td><td class=\"v\"><span id=\"cper\">-</span></td></tr>\n"
  "<tr><td class=\"k\">sense interval</td><td class=\"v\"><span id=\"civ\">-</span></td></tr>\n"
  "<tr><td class=\"k\">measured</td><td class=\"v\"><span id=\"cmeas\">-</span></td></tr>\n"
  "<tr><td class=\"k\">error</td><td class=\"v\"><span id=\"cerr\">-</span></td></tr>\n"
  "</table>\n"
  "<div class=\"row\"><label>bph</label><input id=\"bph\">\n"
  "<label style=\"min-width:78px\">beats/swing</label><input id=\"bps\" style=\"width:48px\">\n"
  "<button onclick=\"cfg('bph,bps')\">Apply</button></div>\n"
  "<div class=\"row\"><label>coils</label>\n"
  "<select id=\"geo\" onchange=\"setgeo()\">\n"
  "<option value=\"1,500\">extremes, opposite</option>\n"
  "<option value=\"1,0\">extremes, same end</option>\n"
  "<option value=\"2,250\">sense centre, drive at extreme</option>\n"
  "<option value=\"\">custom</option></select></div>\n"
  "<div class=\"row\"><label>events/sw</label><input id=\"epp\" style=\"width:48px\">\n"
  "<label style=\"min-width:40px\">offset</label><input id=\"ppt\" style=\"width:62px\">\n"
  "<button onclick=\"cfg('epp,ppt')\">Apply</button></div>\n"
  "<div class=\"note\">Offset is parts per thousand of a full period from a sense event to the bob reaching the drive coil.</div>\n"
  "</section>\n"
  "\n"
  "<section><h2>Sense</h2>\n"
  "<table>\n"
  "<tr><td class=\"k\">detector</td><td class=\"v\"><span id=\"son\" class=\"pill\">-</span></td></tr>\n"
  "<tr><td class=\"k\">tank drive</td><td class=\"v\"><span id=\"stank\">-</span> Hz</td></tr>\n"
  "<tr><td class=\"k\">resonance</td><td class=\"v\"><span id=\"sf0\">-</span></td></tr>\n"
  "<tr><td class=\"k\">baseline / last</td><td class=\"v\"><span id=\"sbase\">-</span></td></tr>\n"
  "<tr><td class=\"k\">events</td><td class=\"v\"><span id=\"sev\">-</span></td></tr>\n"
  "<tr><td class=\"k\">windows</td><td class=\"v\"><span id=\"swin\">-</span></td></tr>\n"
  "</table>\n"
  "<div class=\"row\"><label>scan Hz</label><input id=\"rlo\" value=\"2000\"><input id=\"rhi\" value=\"80000\">\n"
  "<button id=\"scanbtn\" class=\"p\" onclick=\"scan()\">Find resonance</button></div>\n"
  "<canvas id=\"cv\" width=\"600\" height=\"130\"></canvas>\n"
  "<div class=\"row\"><label>tank</label><input id=\"tank\">\n"
  "<label style=\"min-width:56px\">threshold</label><input id=\"thresh\" style=\"width:56px\">\n"
  "<button onclick=\"cfg('tank,thresh')\">Apply</button></div>\n"
  "<div class=\"row\"><label>bob makes</label>\n"
  "<select id=\"falling\"><option value=\"1\">amplitude fall</option><option value=\"0\">amplitude rise</option></select>\n"
  "<button onclick=\"cfg('falling')\">Apply</button>\n"
  "<button id=\"sensebtn\" onclick=\"S&&act('sense&on='+(S.sense.on\?0:1))\">-</button></div>\n"
  "<div class=\"note\">Run the scan with nothing metallic near the coil.</div>\n"
  "</section>\n"
  "\n"
  "<section><h2>Drive</h2>\n"
  "<table>\n"
  "<tr><td class=\"k\">coil</td><td class=\"v\"><span id=\"don\" class=\"pill\">-</span></td></tr>\n"
  "<tr><td class=\"k\">authority</td><td class=\"v\"><span id=\"dauth\">-</span></td></tr>\n"
  "<tr><td class=\"k\">pulses</td><td class=\"v\"><span id=\"dp\">-</span></td></tr>\n"
  "<tr><td class=\"k\">duty budget</td><td class=\"v\"><span id=\"dbud\">-</span> us</td></tr>\n"
  "</table>\n"
  "<div class=\"row\"><label>width us</label><input id=\"pw\">\n"
  "<label style=\"min-width:34px\">adv</label><input id=\"adv\" style=\"width:62px\">\n"
  "<label style=\"min-width:34px\">ret</label><input id=\"ret\" style=\"width:62px\">\n"
  "<button onclick=\"cfg('pw,adv,ret')\">Apply</button></div>\n"
  "<div class=\"row\"><button onclick=\"act('pulse&us='+v('pw'))\">Test pulse</button>\n"
  "<button onclick=\"act('coiloff')\">Coil off</button></div>\n"
  "<div class=\"row\"><label>authority</label><input id=\"auth\" style=\"width:96px\">\n"
  "<button onclick=\"cfg('auth')\">Set ns</button>\n"
  "<button onclick=\"act('measure&n=20&retard=1')\">Measure 20</button></div>\n"
  "<div class=\"note\">Measure needs the loop tracking. Start with a narrow pulse and work up.</div>\n"
  "</section>\n"
  "\n"
  "<section><h2>Time</h2>\n"
  "<table>\n"
  "<tr><td class=\"k\">network</td><td class=\"v\"><span id=\"tnet\">-</span></td></tr>\n"
  "<tr><td class=\"k\">NTP</td><td class=\"v\"><span id=\"tntp\">-</span></td></tr>\n"
  "<tr><td class=\"k\">round trip</td><td class=\"v\"><span id=\"trtt\">-</span> us</td></tr>\n"
  "<tr><td class=\"k\">unix time</td><td class=\"v\"><span id=\"tunix\">-</span></td></tr>\n"
  "<tr><td class=\"k\">crystal</td><td class=\"v\"><span id=\"tppb\">-</span> ppb</td></tr>\n"
  "<tr><td class=\"k\">last offset</td><td class=\"v\"><span id=\"toff\">-</span> us</td></tr>\n"
  "</table>\n"
  "<div class=\"row\"><button onclick=\"act('sync')\">Sync now</button></div>\n"
  "<div class=\"note\">Wi-Fi credentials are set over the serial console with <code>WIFI ssid,pass</code>; they are never served over the network.</div>\n"
  "</section>\n"
  "\n"
  "<section><h2>Configuration</h2>\n"
  "<div class=\"row\"><label>windows %</label><input id=\"rearm\" style=\"width:48px\"><input id=\"minb\" style=\"width:48px\"><input id=\"maxb\" style=\"width:48px\">\n"
  "<button onclick=\"cfg('rearm,minb,maxb')\">Apply</button></div>\n"
  "<div class=\"note\">Rearm, minimum and maximum bump width, as percentages of the sense interval.</div>\n"
  "<div class=\"row\"><label>lock</label><input id=\"acqn\" style=\"width:48px\"><input id=\"acqtol\" style=\"width:48px\">\n"
  "<button onclick=\"cfg('acqn,acqtol')\">Apply</button></div>\n"
  "<div class=\"note\">Events needed to lock, and the gap tolerance in percent.</div>\n"
  "<div class=\"row\" style=\"margin-top:12px\"><button id=\"savebtn\" class=\"p\" onclick=\"act('save')\">Save to flash</button></div>\n"
  "<div class=\"note\">Applied changes take effect at once but are lost on reset until they are saved.</div>\n"
  "</section>\n"
  "\n"
  "</div></div>\n"
  "<script>\n"
  "var S=null,scanning=false;\n"
  "function $(i){return document.getElementById(i)}\n"
  "function v(i){return $(i).value}\n"
  "function t(i,x){var e=$(i);if(e.textContent!=x)e.textContent=x}\n"
  "function num(x){return (x===null||x===undefined)\?'-':(''+x).replace(/\\B(\?=(\\d{3})+(\?!\\d))/g,' ')}\n"
  "function post(u){return fetch(u,{method:'POST'}).then(function(r){return r.json().catch(function(){return{}})})}\n"
  "function act(a){post('/api/action\?do='+a).then(poll)}\n"
  "function cfg(keys){var q=keys.split(',').map(function(k){return k+'='+encodeURIComponent(v(k))}).join('&');\n"
  " post('/api/config\?'+q).then(poll)}\n"
  "function setgeo(){var g=v('geo');if(!g)return;var p=g.split(',');$('epp').value=p[0];$('ppt').value=p[1];cfg('epp,ppt')}\n"
  "function fld(i,x){var e=$(i);if(document.activeElement!==e)e.value=x}\n"
  "\n"
  "function scan(){if(scanning)return;scanning=true;$('scanbtn').disabled=true;\n"
  " post('/api/action\?do=resonance&lo='+v('rlo')+'&hi='+v('rhi'))}\n"
  "\n"
  "function draw(d){var c=$('cv'),g=c.getContext('2d'),W=c.width,H=c.height;\n"
  " var cs=getComputedStyle(document.documentElement);\n"
  " g.clearRect(0,0,W,H);\n"
  " if(!d||!d.n){g.fillStyle=cs.getPropertyValue('--dim');g.font='12px sans-serif';\n"
  "  g.fillText('no scan yet',10,H/2);return}\n"
  " var lo=d.hz[0],hi=d.hz[d.n-1],mn=Math.min.apply(null,d.adc),mx=Math.max.apply(null,d.adc);\n"
  " if(mx<=mn)mx=mn+1;\n"
  " g.strokeStyle=cs.getPropertyValue('--acc');g.lineWidth=2;g.beginPath();\n"
  " for(var i=0;i<d.n;i++){var x=(d.hz[i]-lo)/(hi-lo)*(W-8)+4,y=H-6-(d.adc[i]-mn)/(mx-mn)*(H-20);\n"
  "  i\?g.lineTo(x,y):g.moveTo(x,y)}\n"
  " g.stroke();\n"
  " g.fillStyle=cs.getPropertyValue('--dim');g.font='10px ui-monospace,monospace';\n"
  " g.fillText(lo+' Hz',4,11);var s=hi+' Hz';g.fillText(s,W-g.measureText(s).width-4,11);\n"
  " if(S&&S.res&&S.res.f0>=lo&&S.res.f0<=hi){var fx=(S.res.f0-lo)/(hi-lo)*(W-8)+4;\n"
  "  g.strokeStyle=cs.getPropertyValue('--warn');g.lineWidth=1;g.beginPath();\n"
  "  g.moveTo(fx,4);g.lineTo(fx,H-4);g.stroke()}}\n"
  "\n"
  "function poll(){fetch('/api/status').then(function(r){return r.json()}).then(function(d){\n"
  " S=d;\n"
  " t('net',d.time.net+(d.time.ip!='-'\?' '+d.time.ip:''));\n"
  " t('job',d.job=='idle'\?d.jobmsg:d.job+': '+d.jobmsg);\n"
  " if(scanning&&d.job=='idle'){scanning=false;$('scanbtn').disabled=false;\n"
  "  fetch('/api/scan').then(function(r){return r.json()}).then(draw)}\n"
  "\n"
  " var L=d.loop,e=$('lstate');e.textContent=L.state;\n"
  " e.className='pill '+(L.state=='track'\?'on':L.state=='hold'\?'bad':'off');\n"
  " t('lerr',num(L.err_us));t('lfilt',num(L.filt_us));t('lev',num(L.events)+' ('+L.missed+' missed)');\n"
  " t('ldrift',num(L.drift_ppb));t('lcred',num(L.credit_ns));t('loff',num(L.offset_ms));\n"
  " var b=$('ctlbtn');b.textContent=L.on\?'Stop loop':'Start loop';\n"
  " b.onclick=function(){act('control&on='+(L.on\?0:1))};\n"
  " fld('kp',L.kp);fld('ki',L.ki);fld('slew',L.slew);\n"
  "\n"
  " var C=d.clock;\n"
  " t('cper',(C.period_ns/1e6).toFixed(3)+' ms');\n"
  " t('civ',(C.interval_ns/1e6).toFixed(3)+' ms');\n"
  " t('cmeas',C.mean_us\?(C.mean_us/1000).toFixed(3)+' ms':'-');\n"
  " t('cerr',C.mean_us\?(C.ppb>0\?'+':'')+num(C.ppb)+' ppb, '+(C.sday>0\?'+':'')+C.sday+' s/day':'-');\n"
  " fld('bph',C.bph);fld('bps',C.bps);fld('epp',C.epp);fld('ppt',C.ppt);\n"
  " var gs=C.epp+','+C.ppt;if($('geo').value!=gs)$('geo').value=\n"
  "  [...$('geo').options].some(function(o){return o.value==gs})\?gs:'';\n"
  "\n"
  " var N=d.sense,se=$('son');se.textContent=N.on\?'running':'stopped';\n"
  " se.className='pill '+(N.on\?'on':'off');\n"
  " $('sensebtn').textContent=N.on\?'Stop detector':'Start detector';\n"
  " t('stank',num(N.tank));\n"
  " t('sf0',N.f0\?num(N.f0)+' Hz, Q '+(N.q10/10).toFixed(1):'not calibrated');\n"
  " t('sbase',N.base+' / '+N.last);\n"
  " t('sev',num(N.events)+(N.dropped\?' ('+N.dropped+' dropped)':''));\n"
  " t('swin',(N.rearm/1000).toFixed(0)+' / '+(N.minb/1000).toFixed(0)+'-'+(N.maxb/1000).toFixed(0)+' ms');\n"
  " fld('tank',N.tank);fld('thresh',N.thresh);fld('falling',N.falling);\n"
  "\n"
  " var D=d.drive,de=$('don');de.textContent=D.on\?'ENERGISED':'off';\n"
  " de.className='pill '+(D.on\?'bad':'off');\n"
  " t('dauth',D.auth\?num(D.auth)+' ns/pulse':'not measured');\n"
  " t('dp',num(D.pulses)+(D.refused\?' ('+D.refused+' refused)':''));\n"
  " t('dbud',num(D.budget));\n"
  " fld('pw',D.pw);fld('adv',D.adv);fld('ret',D.ret);fld('auth',D.auth);\n"
  "\n"
  " var T=d.time;t('tnet',T.net);t('tntp',T.ok+' ok, '+T.fail+' failed');\n"
  " t('trtt',num(T.rtt));t('tunix',T.have\?num(T.unix):'not set');\n"
  " t('tppb',(T.ppb>0\?'+':'')+T.ppb+' ('+T.fixes+' fixes)');t('toff',num(T.offset_us));\n"
  "\n"
  " fld('rearm',N.pct[0]);fld('minb',N.pct[1]);fld('maxb',N.pct[2]);\n"
  " fld('acqn',N.acq[0]);fld('acqtol',N.acq[1]);\n"
  " }).catch(function(){t('job','disconnected')})}\n"
  "\n"
  "fetch('/api/scan').then(function(r){return r.json()}).then(draw).catch(function(){});\n"
  "poll();setInterval(poll,1000);\n"
  "</script></body></html>\n"
  "";

const uint32_t web_page_len = (uint32_t)(sizeof(web_page) - 1u);
